name: Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: npm install
      run: |
        npm ci
    - name: npm build
      run: |
        npm run build
      env:
        CI: true