name: Build

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: npm install
      run: |
        npm ci
    - name: npm build
      run: |
        npm run build
    - name: pack
      run: |
        npx electron-builder --publish=never
    - name: upload build
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build/*.*

  release:
    # if: {{ startsWith(github.event.push.commits[0].message, 'chore(release): version ') }}
    # if: github.event.pull_request.merged && github.head_ref == 'prepare-release' && github.event.pull_request.user.login == 'github-actions[bot]'
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: download artifact
      uses: actions/download-artifact@v2
      with:
        name: build
    - name: Prepare Release
      id: prepare_release
      uses: ./.github/actions/prepare-release
    - name: Draft Release
      id: create_release
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ prepare_release.tag }}
        release_name: ${{ prepare_release.release }}
        draft: ${{ prepare_release.draft }}
        prerelease: ${{ prepare_release.prerelease }}
        body: ${{ prepare_release.body }}
    - name: Upload Assets to Release
        uses: ci010/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./build
