name: Build

on:
  push:
    branches:
      - dev
  # pull_request:
  #   type: [closed]
  #   branches:
  #     - master
    
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: npm install
      run: |
        npm ci
    - name: npm build
      run: |
        npm run build
    - name: pack
      run: |
        npx electron-builder --publish=never
    - name: upload build
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build/*.*

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: download artifact
      uses: actions/download-artifact@v2
      with:
        name: build
    - name: Draft Release
      id: create_release
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: true
