name: Prepare Release

on:
  push:
    branches: 
      - master

jobs:
  repare-release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: |
        npm ci
      env:
        CI: true
    - name: Build
      run: |
        npm run build
    - name: Bump Version
      id: version
      uses: ./.github/actions/bump-version

    - name: Prepare Pull Reuqest
      if: ${{ steps.version.release == 'true' }}
      id: pr
      uses: ./.github/actions/prepare-pr

    - name: Create Pull Request
      if: ${{ steps.version.release == 'true' }}
      uses: peter-evans/create-pull-request@v1.4.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMIT_MESSAGE: ${{ steps.pr.outputs.commit_message }}
        PULL_REQUEST_TITLE: ${{ steps.pr.outputs.pr_title }}
        PULL_REQUEST_BODY: ${{ steps.pr.outputs.pr_body }}
        PULL_REQUEST_ASSIGNEES: ci010
        PULL_REQUEST_REVIEWERS: ci010
        PULL_REQUEST_BRANCH: prepare-release
        BRANCH_SUFFIX: none


